<?php


namespace App\Facades;


use Illuminate\Support\Facades\Facade;

class MysqlMg extends Facade
{


    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
//    protected static function getFacadeAccessor()
//    {
//        return 'mysqlmg';
//    }
}
